### ISSUE TITLE
'compute': is not a member of 'pcl::UniformSampling<pcl::PointXYZ>'	cloud_registraion_feature_base	

### ISSUE THREAD

**Issue by yonelay11** [UnaNancyOwen/Tutorials#1]
I'm really interesting your PointCloud tutorials. In example2, point cloud registration with featrue base approach that shows this error **-'compute': is not a member of 'pcl::UniformSampling<pcl::PointXYZ>'	cloud_registraion_feature_base	**. Let me know where I made wrong.

**Comment by UnaNancyOwen** [comment]
@yonelay11 This project is no longer actively maintained.
Please refer to [upstream](https://github.com/PointCloudLibrary/pcl), and use [latest release](https://github.com/PointCloudLibrary/pcl/releases/tag/pcl-1.8.1).
